# Generated by gpt4o

from mininet.net import Mininet
from mininet.node import RemoteController
from mininet.cli import CLI
from mininet.log import setLogLevel

def setup_bus_network(host_count=30, switch_count=5, controllers=None):
    """Sets up a bus topology network with specified hosts and switches."""
    if controllers is None:
        controllers = {
            'c1': ('127.0.0.1', 6633),
            'c2': ('127.0.0.1', 6634),
            'c3': ('127.0.0.1', 6635)
        }

    net = Mininet()

    # Add controllers
    for name, (ip, port) in controllers.items():
        net.addController(name, controller=RemoteController, ip=ip, port=port)

    # Add switches
    switches = []
    for i in range(1, switch_count + 1):
        switch = net.addSwitch(f's{i}')
        switches.append(switch)

    # Add hosts and connect them to switches
    hosts = []
    hosts_per_switch = host_count // switch_count
    for i in range(1, host_count + 1):
        host = net.addHost(f'h{i}')
        hosts.append(host)
        switch_index = (i - 1) // hosts_per_switch
        net.addLink(host, switches[switch_index])

    # Connect switches in a linear (bus) topology
    for i in range(len(switches) - 1):
        net.addLink(switches[i], switches[i + 1])

    # Assign switches to controllers for redundancy
    controller_assignments = {
        's1': [net.get('c1'), net.get('c2')],
        's2': [net.get('c1'), net.get('c2')],
        's3': [net.get('c2'), net.get('c3')],
        's4': [net.get('c2'), net.get('c3')],
        's5': [net.get('c1'), net.get('c3')],
    }

    for switch_name, controller_list in controller_assignments.items():
        net.get(switch_name).start(controller_list)

    net.start()
    CLI(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel('info')
    setup_bus_network() 