# Generated by Claude-3.5-Sonnet

from mininet.net import Mininet
from mininet.node import RemoteController
from mininet.cli import CLI
from mininet.log import setLogLevel

def createNetwork():
    net = Mininet()
    
    # Add controllers
    c1 = net.addController('c1', controller=RemoteController, ip='127.0.0.1', port=6633)
    c2 = net.addController('c2', controller=RemoteController, ip='127.0.0.1', port=6634)
    c3 = net.addController('c3', controller=RemoteController, ip='127.0.0.1', port=6635)
    
    # Add switches
    switches = []
    for i in range(5):
        switch = net.addSwitch(f's{i+1}')
        switches.append(switch)
    
    # Add hosts
    hosts = []
    for i in range(10):
        host = net.addHost(f'h{i+1}')
        hosts.append(host)
        # Connect each host to the nearest switch in bus topology
        switch_index = i // 2
        net.addLink(host, switches[switch_index])
    
    # Connect switches in a bus topology
    for i in range(len(switches)-1):
        net.addLink(switches[i], switches[i+1])
    
    net.start()
    CLI(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel('info')
    createNetwork() 