# Generated by Claude-3.5-Sonnet

from mininet.net import Mininet
from mininet.node import RemoteController
from mininet.cli import CLI
from mininet.log import setLogLevel

def createNetwork():
    net = Mininet()
    
    # Add controllers with specific control domains
    c1 = net.addController('c1', controller=RemoteController, ip='127.0.0.1', port=6633)
    c2 = net.addController('c2', controller=RemoteController, ip='127.0.0.1', port=6634)
    c3 = net.addController('c3', controller=RemoteController, ip='127.0.0.1', port=6635)
    
    # Add switches
    s1 = net.addSwitch('s1')  # Central switch
    s2 = net.addSwitch('s2')
    s3 = net.addSwitch('s3')
    s4 = net.addSwitch('s4')
    s5 = net.addSwitch('s5')
    
    # Add hosts and connect them to central switch
    hosts = []
    for i in range(30):
        host = net.addHost(f'h{i+1}')
        hosts.append(host)
        net.addLink(host, s1)
    
    # Connect switches in star topology
    net.addLink(s1, s2)
    net.addLink(s1, s3)
    net.addLink(s1, s4)
    net.addLink(s1, s5)
    
    # Assign switches to controllers
    s1.start([c1, c2])  # Central switch controlled by c1 and c2
    s2.start([c2, c3])  # Edge switches controlled by c2 and c3
    s3.start([c2, c3])
    s4.start([c1, c3])
    s5.start([c1, c3])
    
    net.start()
    CLI(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel('info')
    createNetwork() 