#!/usr/bin/env python
#this is generated by claude sonnet and this works as per simple_switch_13.py script. 
# so the network has to be designed in mind using the controller type. 
from mininet.net import Mininet
from mininet.node import RemoteController, OVSSwitch
from mininet.cli import CLI
from mininet.link import TCLink
from mininet.log import setLogLevel

def createNetwork():
    # Initialize network
    net = Mininet(switch=OVSSwitch, link=TCLink)
    
    # Adding controllers
    c1 = net.addController('c1', controller=RemoteController, ip='127.0.0.1', port=6633)
    c2 = net.addController('c2', controller=RemoteController, ip='127.0.0.1', port=6634)
    
    # Adding switches (5 switches)
    switches = []
    for i in range(1, 6):
        switch = net.addSwitch(f's{i}', protocols='OpenFlow13')
        switches.append(switch)
    
    # Adding hosts (10 hosts)
    hosts = []
    for i in range(1, 11):
        host = net.addHost(f'h{i}', ip=f'10.0.0.{i}/24')
        hosts.append(host)
    
    # Create mesh topology: Connect every switch to every other switch
    for i in range(len(switches)):
        for j in range(i + 1, len(switches)):
            net.addLink(switches[i], switches[j])
    
    # Connect hosts to switches
    net.addLink(hosts[0], switches[0])
    net.addLink(hosts[1], switches[0])
    net.addLink(hosts[2], switches[1])
    net.addLink(hosts[3], switches[1])
    net.addLink(hosts[4], switches[2])
    net.addLink(hosts[5], switches[2])
    net.addLink(hosts[6], switches[3])
    net.addLink(hosts[7], switches[3])
    net.addLink(hosts[8], switches[4])
    net.addLink(hosts[9], switches[4])
    
    # Build and start network
    net.build()
    net.start()
    
    # Enable STP on all switches
    for switch in switches:
        print(f"Enabling STP on {switch.name}")
        switch.cmd('ovs-vsctl set Bridge', switch, 'stp_enable=true')
        
    # Wait a bit for STP to converge
    print("Waiting for STP convergence...")
    from time import sleep
    sleep(10)
    
    return net

if __name__ == '__main__':
    setLogLevel('info')
    net = createNetwork()
    CLI(net)
    net.stop()